name: test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    # At 23:25 on Thursday.
    - cron: "25 23 * * 4"

jobs:
  test-octave-only:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install octave
        run: sudo apt update && sudo apt install -y octave
      - name: Run test
        run: cd MultiCamSelfCal && octave gocal.m --config=../strawlab/test-data/DATA20100906_134124/no-global-iterations.cfg

  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
        python-version: [ '3.8', '3.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Install octave
        run: sudo apt update && sudo apt install -y octave
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python MCSC wrapper
        run: pip install . -v
      - name: Install pytest testing framework
        run: pip install pytest
      - name: Test Python wrapper
        run: pytest
